# Generated by Django 6.0 on 2026-02-25 07:16

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral'), ('website', 'Website'), ('direct', 'Direct'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.inquiry_document_path),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='document_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='follow_up_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('product', 'Product Inquiry'), ('service', 'Service Inquiry')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='terms',
            field=models.CharField(blank=True, choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
