# Generated by Django 5.2.12 on 2026-03-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales_user', 'SalesUser'), ('sourcing_user', 'SourcingUser'), ('sourcing_manager', 'SourcingManager'), ('operation_user', 'OperationUser')], default='sales_user', max_length=30),
        ),
    ]
